# fly.toml app configuration file generated for falling-water-7812 on 2023-11-01T19:55:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "falling-water-7812"
primary_region = "jnb"

[build]


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
